import {mkdirSync} from 'node:fs';
import path from 'node:path';
import {rebuild} from './db.ts';
import {commitIndexRebuild} from './git.ts';
import {excerpt, validNotes} from './notes.ts';
import {TYPE_DIRS, type Note} from './schema.ts';
import type {EmbeddingProvider} from './embedding.ts';

function header(id: string, title: string, today: string): string {
	return `---\nid: ${id}\ntype: index\ntitle: ${title}\ncreated: ${today}\nupdated: ${today}\nstatus: active\ntags: []\n---\n\n## Purpose\n\nGenerated index.\n\n## Key Links\n\n`;
}

function link(n: Note, indexDir: string): string {
	const ex = excerpt(n);
	const rel = path.relative(indexDir, n.path);
	const base = `- [${n.meta.title ?? n.path}](${rel}) — \`${n.meta.type}\` · ${n.meta.status}`;
	return ex ? base + '\n  ' + ex + '\n' : base + '\n';
}

function footer(section: string): string {
	return `\n## Open Questions\n\n${section}\n\n## Recent Changes\n\nGenerated by pk index.\n`;
}

export async function buildIndexFiles(knowledgeDir: string, provider?: EmbeddingProvider): Promise<{indexDir: string; ftsCount: number}> {
	const ftsCount = await rebuild(knowledgeDir, provider);
	const today = new Date().toISOString().slice(0, 10);
	const notes = await validNotes(knowledgeDir, ['index']);
	const indexDir = path.join(knowledgeDir, TYPE_DIRS.index ?? 'indexes');
	mkdirSync(indexDir, {recursive: true});

	const mkLink = (n: Note) => link(n, indexDir);

	await Bun.write(
		path.join(indexDir, 'all.md'),
		header('index-all', 'All Knowledge', today) + notes.map(mkLink).join('') + footer('See open-questions.md.'),
	);

	const decisions = notes.filter(n => n.meta.type === 'decision');
	await Bun.write(
		path.join(indexDir, 'decisions.md'),
		header('index-decisions', 'Decisions', today) + decisions.map(mkLink).join('') + footer('N/A.'),
	);

	const openQ = notes.filter(n => n.meta.type === 'question' && n.meta.status === 'open');
	await Bun.write(
		path.join(indexDir, 'open-questions.md'),
		header('index-open-questions', 'Open Questions', today)
		+ openQ.map(mkLink).join('')
		+ footer(openQ.length > 0 ? openQ.map(n => `- ${n.meta.title ?? n.path}`).join('\n') : 'None currently open.'),
	);

	const byTag = new Map<string, Note[]>();
	for (const n of notes) {
		for (const tag of n.meta.tags ?? []) {
			if (!byTag.has(tag)) {
				byTag.set(tag, []);
			}

			byTag.get(tag)!.push(n);
		}
	}

	let tagsBody = header('index-tags', 'Tags', today);
	for (const [tag, tn] of [...byTag.entries()].toSorted(([a], [b]) => a.localeCompare(b))) {
		tagsBody += `### ${tag}\n\n` + tn.map(mkLink).join('') + '\n';
	}

	await Bun.write(path.join(indexDir, 'tags.md'), tagsBody + footer('See open-questions.md.'));

	await commitIndexRebuild(knowledgeDir);
	return {ftsCount, indexDir};
}
