import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import type { Command } from 'commander'
import { TYPE_DIRS } from '../lib/notes.ts'

const KNOWLEDGE_DIR = 'knowledge'

export function registerInit(program: Command): void {
  program
    .command('init')
    .description('Initialize knowledge base and install agent hook')
    .option('--harness <harness>', 'Agent harness: claude (default)', 'claude')
    .action((opts: { harness: string }) => {
      for (const dir of Object.values(TYPE_DIRS)) {
        mkdirSync(path.join(KNOWLEDGE_DIR, dir), { recursive: true })
      }
      console.log('created knowledge/ directories')
      const gi = path.join(KNOWLEDGE_DIR, '.gitignore')
      if (!existsSync(gi)) {
        writeFileSync(gi, '.index.db\n')
        console.log('created knowledge/.gitignore')
      }
      if (opts.harness === 'claude') installClaudeHook()
      else console.log(`Unsupported harness: ${opts.harness}. Only claude supported.`)
      console.log('\npk init complete. Run pk index after adding notes.')
    })
}

function installClaudeHook(): void {
  mkdirSync(path.join('.claude', 'hooks'), { recursive: true })
  const hookFile = path.join('.claude', 'hooks', 'pk-user-prompt-submit.ts')
  writeFileSync(hookFile, HOOK_TEMPLATE)
  console.log(`wrote ${hookFile}`)
  const settingsFile = path.join('.claude', 'settings.json')
  let settings: Record<string, unknown> = {}
  if (existsSync(settingsFile)) {
    try { settings = JSON.parse(readFileSync(settingsFile, 'utf8')) as Record<string, unknown> } catch {}
  }
  const hooks = (settings['hooks'] as Record<string, string[]> | undefined) ?? {}
  const existing: string[] = (hooks['UserPromptSubmit'] as string[] | undefined) ?? []
  const cmd = `bun ${hookFile} user-prompt-submit`
  if (!existing.includes(cmd)) hooks['UserPromptSubmit'] = [...existing, cmd]
  settings['hooks'] = hooks
  writeFileSync(settingsFile, JSON.stringify(settings, null, 2) + '\n')
  console.log('updated .claude/settings.json')
}

const HOOK_TEMPLATE = `// pk hook — auto-generated by pk init
async function runPk(args: string[]): Promise<string> {
  const child = Bun.spawn(['pk', ...args], { stdout: 'pipe', stderr: 'pipe' })
  const [out] = await Promise.all([new Response(child.stdout).text(), child.exited])
  return out.trim()
}

async function handleUserPromptSubmit() {
  const input = JSON.parse(await Bun.stdin.text()) as { prompt?: string }
  const query = input.prompt?.trim() ?? ''
  let context = ''
  try {
    const args = ['synthesize', '--session-start', '--limit', '8']
    if (query) args.push(query)
    context = await runPk(args)
  } catch {}
  console.log(JSON.stringify({
    hookSpecificOutput: { hookEventName: 'UserPromptSubmit', additionalContext: context },
    suppressOutput: true,
  }))
}

const event = process.argv[2] ?? ''
if (event === 'user-prompt-submit') handleUserPromptSubmit().catch(() => process.exit(0))
else process.exit(0)
`
