import {mkdirSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import type {Command} from 'commander';
import {rebuild} from '../lib/db.ts';
import {
	excerpt, validNotes, TYPE_DIRS, type Note,
} from '../lib/notes.ts';
import {findKnowledgeDir} from '../lib/paths.ts';

export function registerRebuild(program: Command): void {
	program
		.command('index')
		.description('Rebuild FTS5 search index and markdown index files')
		.action(() => {
			const knowledgeDir = findKnowledgeDir();
			const count = rebuild(knowledgeDir);
			console.log(`indexed ${count} notes`);
			const today = new Date().toISOString().slice(0, 10);
			const notes = validNotes(knowledgeDir, ['index']);
			const indexDir = path.join(knowledgeDir, TYPE_DIRS.index ?? 'indexes');
			mkdirSync(indexDir, {recursive: true});
			function header(id: string, title: string): string {
				return `---\nid: ${id}\ntype: index\ntitle: ${title}\ncreated: ${today}\nupdated: ${today}\nstatus: active\ntags: []\n---\n\n## Purpose\n\nGenerated index.\n\n## Key Links\n\n`;
			}

			function link(n: (typeof notes)[number]): string {
				const ex = excerpt(n);
				const rel = path.relative(indexDir, n.path);
				const base = `- [${n.meta.title ?? n.path}](${rel}) — \`${n.meta.type}\` · ${n.meta.status}`;
				return ex ? base + '\n  ' + ex + '\n' : base + '\n';
			}

			const footer = (section: string) => `\n## Open Questions\n\n${section}\n\n## Recent Changes\n\nGenerated by pk index.\n`;
			writeFileSync(path.join(indexDir, 'all.md'), header('index-all', 'All Knowledge') + notes.map(link).join('') + footer('See open-questions.md.'));
			const decisions = notes.filter(n => n.meta.type === 'decision');
			writeFileSync(path.join(indexDir, 'decisions.md'), header('index-decisions', 'Decisions') + decisions.map(link).join('') + footer('N/A.'));
			const openQ = notes.filter(n => n.meta.type === 'question' && n.meta.status === 'open');
			writeFileSync(path.join(indexDir, 'open-questions.md'), header('index-open-questions', 'Open Questions') + openQ.map(link).join('') + footer(openQ.length > 0 ? openQ.map(n => `- ${n.meta.title ?? n.path}`).join('\n') : 'None currently open.'));
			const byTag = new Map<string, Note[]>();
			for (const n of notes) {
				for (const tag of n.meta.tags ?? []) {
					if (!byTag.has(tag)) {
						byTag.set(tag, []);
					}

					byTag.get(tag)!.push(n);
				}
			}

			let tagsBody = header('index-tags', 'Tags');
			for (const [tag, tn] of [...byTag.entries()].toSorted(([a], [b]) => a.localeCompare(b))) {
				tagsBody += `### ${tag}\n\n` + tn.map(link).join('') + '\n';
			}

			writeFileSync(path.join(indexDir, 'tags.md'), tagsBody + footer('See open-questions.md.'));
			console.log(`wrote indexes to ${indexDir}`);
		});
}
