import {mkdirSync} from 'node:fs';
import path from 'node:path';

async function readJson(filePath: string): Promise<Record<string, unknown>> {
	try {
		return JSON.parse(await Bun.file(filePath).text()) as Record<string, unknown>;
	} catch {
		return {};
	}
}

async function writeJson(filePath: string, data: unknown): Promise<void> {
	mkdirSync(path.dirname(filePath), {recursive: true});
	await Bun.write(filePath, JSON.stringify(data, null, 2) + '\n');
}

function sessionStartScript(knowledgeDir: string): string {
	return `\
#!/bin/bash
# pk hook — auto-generated by pk init
if [ -n "$CLAUDE_ENV_FILE" ]; then
  echo 'export PK_KNOWLEDGE_DIR=${knowledgeDir}' >> "$CLAUDE_ENV_FILE"
fi
exit 0
`;
}

function userPromptSubmitScript(): string {
	return `\
// pk hook — auto-generated by pk init
async function handleUserPromptSubmit() {
  const proc = Bun.spawnSync(['pk', 'prime']);
  const output = proc.stdout?.toString().trim() ?? '';
  console.log(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'UserPromptSubmit',
      additionalContext: output,
    },
    suppressOutput: true,
  }));
}

handleUserPromptSubmit().catch(() => process.exit(0));
`;
}

function addHookEntry(
	hooks: Record<string, unknown>,
	event: string,
	command: string,
): void {
	const entries = (hooks[event] as Array<Record<string, unknown>> | undefined) ?? [];
	const wrappedHook = {matcher: '', hooks: [{type: 'command', command}]};
	const alreadyPresent = (entry: Record<string, unknown>) =>
		Array.isArray(entry.hooks)
		&& entry.hooks.some(
			(h: unknown) =>
				typeof h === 'object'
				&& h !== null
				&& (h as Record<string, unknown>).command === command,
		);
	if (!entries.some(alreadyPresent)) {
		entries.push(wrappedHook);
	}

	hooks[event] = entries;
}

export async function writeClaudeHook(projectRoot: string, knowledgeDir: string): Promise<void> {
	const hookDir = path.join(projectRoot, '.claude', 'hooks');
	mkdirSync(hookDir, {recursive: true});

	const sessionStartPath = path.join(hookDir, 'pk-session-start.sh');
	await Bun.write(sessionStartPath, sessionStartScript(knowledgeDir));
	const {chmodSync} = await import('node:fs');
	chmodSync(sessionStartPath, 0o755);

	const evalPath = path.join(hookDir, 'pk-eval.ts');
	await Bun.write(evalPath, userPromptSubmitScript());

	const settingsPath = path.join(projectRoot, '.claude', 'settings.json');
	const settings = await readJson(settingsPath);
	const hooks = (settings.hooks as Record<string, unknown> | undefined) ?? {};

	addHookEntry(hooks, 'SessionStart', sessionStartPath);
	addHookEntry(hooks, 'UserPromptSubmit', `bun run ${evalPath}`);

	settings.hooks = hooks;
	await writeJson(settingsPath, settings);
}
