import {mkdirSync} from 'node:fs';
import path from 'node:path';

async function readJson(filePath: string): Promise<Record<string, unknown>> {
	try {
		return JSON.parse(await Bun.file(filePath).text()) as Record<string, unknown>;
	} catch {
		return {};
	}
}

async function writeJson(filePath: string, data: unknown): Promise<void> {
	mkdirSync(path.dirname(filePath), {recursive: true});
	await Bun.write(filePath, JSON.stringify(data, null, 2) + '\n');
}

function userPromptSubmitScript(): string {
	return `\
// pk hook — auto-generated by pk init
async function handleUserPromptSubmit() {
  const proc = Bun.spawnSync(['pk', 'prime']);
  const output = proc.stdout?.toString().trim() ?? '';
  console.log(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'UserPromptSubmit',
      additionalContext: output,
    },
    suppressOutput: true,
  }));
}

handleUserPromptSubmit().catch(() => process.exit(0));
`;
}

function addHookEntry(
	hooks: Record<string, unknown>,
	event: string,
	command: string,
): void {
	const entries = (hooks[event] as Array<Record<string, unknown>> | undefined) ?? [];
	const wrappedHook = {matcher: '', hooks: [{type: 'command', command}]};
	const alreadyPresent = (entry: Record<string, unknown>) =>
		Array.isArray(entry.hooks)
		&& entry.hooks.some((h: unknown) =>
			typeof h === 'object'
			&& h !== null
			&& (h as Record<string, unknown>).command === command);
	if (!entries.some(alreadyPresent)) {
		entries.push(wrappedHook);
	}

	hooks[event] = entries;
}

/**
 * Remove the legacy SessionStart pk hook that injected PK_KNOWLEDGE_DIR.
 * No longer needed — pk discovers .pk.json by walking up from CWD.
 */
function removeLegacySessionStartHook(hooks: Record<string, unknown>): void {
	const entries = hooks.SessionStart as Array<Record<string, unknown>> | undefined;
	if (!entries) {
		return;
	}

	const filtered = entries.filter(entry => {
		const hookList = entry.hooks as Array<Record<string, unknown>> | undefined;
		return !hookList?.some(h => typeof h.command === 'string' && h.command.endsWith('pk-session-start.sh'));
	});

	if (filtered.length === 0) {
		delete hooks.SessionStart;
	} else {
		hooks.SessionStart = filtered;
	}
}

export async function writeClaudeHook(projectRoot: string): Promise<void> {
	const hookDir = path.join(projectRoot, '.claude', 'hooks');
	mkdirSync(hookDir, {recursive: true});

	const evalPath = path.join(hookDir, 'pk-eval.ts');
	await Bun.write(evalPath, userPromptSubmitScript());

	const settingsPath = path.join(projectRoot, '.claude', 'settings.json');
	const settings = await readJson(settingsPath);
	const hooks = (settings.hooks as Record<string, unknown> | undefined) ?? {};

	removeLegacySessionStartHook(hooks);
	addHookEntry(hooks, 'UserPromptSubmit', `bun run ${evalPath}`);

	settings.hooks = hooks;
	await writeJson(settingsPath, settings);
}
