import {mkdirSync} from 'node:fs';
import path from 'node:path';

async function readJson(filePath: string): Promise<Record<string, unknown>> {
	try {
		return JSON.parse(await Bun.file(filePath).text()) as Record<string, unknown>;
	} catch {
		return {};
	}
}

async function writeJson(filePath: string, data: unknown): Promise<void> {
	mkdirSync(path.dirname(filePath), {recursive: true});
	await Bun.write(filePath, JSON.stringify(data, null, 2) + '\n');
}

function claudeHookScript(knowledgeDir: string): string {
	return `\
// pk hook — auto-generated by pk init
async function handleUserPromptSubmit() {
  const proc = Bun.spawnSync(['pk', 'prime'], {
    env: { ...process.env, PK_KNOWLEDGE_DIR: '${knowledgeDir}' }
  });
  const output = proc.stdout?.toString().trim() ?? '';
  console.log(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'UserPromptSubmit',
      additionalContext: output,
    },
    suppressOutput: true,
  }));
}

handleUserPromptSubmit().catch(() => process.exit(0));
`;
}

export async function writeClaudeHook(projectRoot: string, knowledgeDir: string): Promise<void> {
	const hookDir = path.join(projectRoot, '.claude', 'hooks');
	const hookPath = path.join(hookDir, 'pk-eval.ts');
	mkdirSync(hookDir, {recursive: true});
	await Bun.write(hookPath, claudeHookScript(knowledgeDir));

	const settingsPath = path.join(projectRoot, '.claude', 'settings.json');
	const settings = await readJson(settingsPath);
	const hooks = (settings.hooks as Record<string, unknown> | undefined) ?? {};
	const ups = (hooks.UserPromptSubmit as Array<Record<string, unknown>> | undefined) ?? [];
	const hookCmd = `bun run ${hookPath}`;
	const wrappedHook = {
		matcher: '',
		hooks: [
			{
				type: 'command',
				command: hookCmd,
			},
		],
	};

	const hasPkEval = (entry: Record<string, unknown>) =>
		typeof entry === 'object'
		&& entry !== null
		&& 'hooks' in entry
		&& Array.isArray(entry.hooks)
		&& entry.hooks.some((hook: unknown) =>
			typeof hook === 'object'
			&& hook !== null
			&& 'type' in hook
			&& hook.type === 'command'
			&& 'command' in hook
			&& hook.command === hookCmd);

	if (!ups.some(hasPkEval)) {
		ups.push(wrappedHook);
	}

	hooks.UserPromptSubmit = ups;
	settings.hooks = hooks;
	await writeJson(settingsPath, settings);
}
