import {mkdirSync} from 'node:fs';
import path from 'node:path';
import {readJson, writeJson, resolvePkCommand} from './shared.ts';

async function writeToml(filePath: string, content: string): Promise<void> {
	mkdirSync(path.dirname(filePath), {recursive: true});
	await Bun.write(filePath, content);
}

export async function writeCodexConfig(projectRoot: string, knowledgeDir: string): Promise<void> {
	const cfgPath = path.join(projectRoot, '.codex', 'config.toml');
	const pkCmd = resolvePkCommand();
	const toml = `\
[mcp_servers.pk]
command = "${pkCmd}"
args = ["mcp"]
env = { PK_KNOWLEDGE_DIR = "${knowledgeDir}" }
`;
	await writeToml(cfgPath, toml);
}

function codexHookScript(): string {
	return `\
#!/bin/bash
# pk forced-eval hook — auto-generated by pk init
# Output JSON to stdout

cat <<EOF
{
  "continue": true,
  "suppressOutput": false
}
EOF
`;
}

export async function writeCodexHook(projectRoot: string): Promise<void> {
	const hookPath = path.join(projectRoot, '.codex', 'hooks', 'pk-eval.sh');
	mkdirSync(path.dirname(hookPath), {recursive: true});
	await Bun.write(hookPath, codexHookScript());

	const hooksPath = path.join(projectRoot, '.codex', 'hooks.json');
	const hooks = await readJson(hooksPath);
	const hooksObj = (hooks.hooks as Record<string, unknown> | undefined) ?? {};
	const ups = (hooksObj.UserPromptSubmit as Array<Record<string, unknown>> | undefined) ?? [];
	if (!ups.some(h => typeof h === 'object' && h !== null && 'command' in h && typeof h.command === 'string' && h.command.includes('pk-eval'))) {
		ups.push({command: hookPath});
	}

	hooksObj.UserPromptSubmit = ups;
	hooks.hooks = hooksObj;
	await writeJson(hooksPath, hooks);
}
