import {mkdirSync} from 'node:fs';
import path from 'node:path';
import {
	readJson,
	writeJson,
	resolvePkCommand,
	FORCED_EVAL_PROMPT,
} from './shared.ts';

export async function writeOpenCodeConfig(projectRoot: string, knowledgeDir: string): Promise<void> {
	const cfgPath = path.join(projectRoot, 'opencode.json');
	const cfg = await readJson(cfgPath);
	const mcp = (cfg.mcp as Record<string, unknown> | undefined) ?? {};
	const pkCmd = resolvePkCommand();
	mcp.pk = {
		type: 'local',
		enabled: true,
		command: [pkCmd, 'mcp'],
		environment: {PK_KNOWLEDGE_DIR: knowledgeDir},
	};
	cfg.mcp = mcp;
	await writeJson(cfgPath, cfg);
}

function openCodePluginScript(): string {
	return `\
// pk forced-eval plugin — auto-generated by pk init
export const experimental = {
	async 'chat.system.transform'({ system }: { system: string[] }): Promise<void> {
	   system.unshift(${JSON.stringify(FORCED_EVAL_PROMPT)});
	},
};
`;
}

export async function writeOpenCodePlugin(projectRoot: string): Promise<void> {
	const pluginPath = path.join(projectRoot, '.opencode', 'plugins', 'pk-eval.ts');
	mkdirSync(path.dirname(pluginPath), {recursive: true});
	await Bun.write(pluginPath, openCodePluginScript());
}
