import {mkdirSync} from 'node:fs';
import path from 'node:path';

function openCodePluginScript(knowledgeDir: string): string {
	return `\
// pk plugin — auto-generated by pk init
export const experimental = {
	async 'chat.system.transform'({ system }: { system: string[] }): Promise<void> {
	   const proc = Bun.spawnSync(['pk', 'prime'], {
	     env: { ...process.env, PK_KNOWLEDGE_DIR: '${knowledgeDir}' }
	   });
	   const output = proc.stdout?.toString().trim() ?? '';
	   if (output) {
	     system.unshift(output);
	   }
	},
};
`;
}

export async function writeOpenCodePlugin(projectRoot: string, knowledgeDir: string): Promise<void> {
	const pluginPath = path.join(projectRoot, '.opencode', 'plugins', 'pk-eval.ts');
	mkdirSync(path.dirname(pluginPath), {recursive: true});
	await Bun.write(pluginPath, openCodePluginScript(knowledgeDir));
}
