import {mkdirSync} from 'node:fs';
import path from 'node:path';

function openCodePluginScript(): string {
	return `\
// pk plugin — auto-generated by pk init
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';

function getKnowledgeDir(): string {
  try {
    const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
    const cfg = JSON.parse(readFileSync(path.join(root, '.pk.json'), 'utf8')) as {knowledgeDir?: string};
    return cfg.knowledgeDir ?? '';
  } catch {
    return '';
  }
}

export const pkPlugin = async (_input: unknown) => ({
  'shell.env': async (
    _input: unknown,
    output: { env: Record<string, string> },
  ): Promise<void> => {
    const dir = getKnowledgeDir();
    if (dir) output.env.PK_KNOWLEDGE_DIR = dir;
  },
  'experimental.chat.system.transform': async (
    _input: unknown,
    output: { system: string[] },
  ): Promise<void> => {
    const proc = Bun.spawnSync(['pk', 'prime']);
    const text = proc.stdout?.toString().trim() ?? '';
    if (text) output.system.unshift(text);
  },
});
`;
}

export async function writeOpenCodePlugin(projectRoot: string): Promise<void> {
	const pluginPath = path.join(projectRoot, '.opencode', 'plugins', 'pk-eval.ts');
	mkdirSync(path.dirname(pluginPath), {recursive: true});
	await Bun.write(pluginPath, openCodePluginScript());
}
