import {mkdirSync} from 'node:fs';
import path from 'node:path';

function piPluginScript(knowledgeDir: string): string {
	return `\
// pk extension — auto-generated by pk init
import { spawnSync } from 'node:child_process';
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent';

export default function (pi: ExtensionAPI) {
  pi.on('before_agent_start', async (event, _ctx) => {
    const proc = spawnSync('pk', ['prime'], {
      env: { ...process.env, PK_KNOWLEDGE_DIR: '${knowledgeDir}' },
      encoding: 'utf-8',
    });
    const output = proc.stdout?.trim() ?? '';
    return output
      ? { systemPrompt: output + '\\n\\n' + event.systemPrompt }
      : undefined;
  });

  pi.on('tool_call', async (event, _ctx) => {
    if (event.toolName === 'bash' && event.input?.command) {
      event.input.command = 'export PK_KNOWLEDGE_DIR=${knowledgeDir}\\n' + event.input.command;
    }
  });
}
`;
}

export async function writePiPlugin(projectRoot: string, knowledgeDir: string): Promise<void> {
	const pluginPath = path.join(projectRoot, '.pi', 'extensions', 'pk-eval.ts');
	mkdirSync(path.dirname(pluginPath), {recursive: true});
	await Bun.write(pluginPath, piPluginScript(knowledgeDir));
}
